services:
  web:
    build:
      context: .
      dockerfile: bot/dockerfile-dev
    container_name: bot_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://hoyt:hutyro@db:5432/app_db
    depends_on:
      - db

  db:
    image: postgres:17.2
    container_name: bot_db
    restart: always
    environment:
      POSTGRES_USER: hoyt
      POSTGRES_PASSWORD: hutyro
      POSTGRES_DB: app_db
    volumes:  # Монтируем данные для сохранения между перезапусками
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  db_data: