# Используем официальный образ Python
FROM python:3.13.1-slim-bookworm

# Установите необходимые утилиты
RUN apt-get update && apt-get install -y \
    curl \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию
WORKDIR /app
ENV PYTHONPATH=/app

# Копируем файл зависимостей
COPY ../requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY . .

# Указываем порт, который будет слушать приложение
EXPOSE 5000

# Запускаем приложение
CMD ["python", "bot/main.py"]
